EasyCrypt/easycrypt

config/tests.config, scripts/testing/runtest
This extends the runtest script with recursive exclusions, and makes the examples/incomplete exclusion recursive.
Submitted as a pull request for code review/refactoring and checking that it does not break things downstream.
=> Recursively exclude examples/incomplete from testing targets

src/phl/ecPhlPrRw.ml
Implemented rewrite Pr [...] for mu_ge0 and mu_le1, corresponding to the Distr.ec lemmas
lemma ge0_mu (d : 'a distr) p : 0%r <= mu d p.
lemma le1_mu (d : 'a distr) p : mu d p <= 1%r.
=> Implemented rewrite Pr [...] for mu_ge0 and mu_le1

src/ecParser.mly, src/ecScope.ml
The elements of prover [...] have one of the following forms, where s
is a string:
s (add s to the use-only list)
+s (add include s to the include/exclude list)
-s (add exclude s to the include/exclude list)
The include/exclude list is ordered, so that later instructions can
supersede earlier ones. The use-only list was not ordered, but now
is. The relative order of the use-only and include/exclude lists
is irrelevant, so that, e.g., prover ["Z3" +"Alt-Ergo"] and prover
[+"Alt-Ergo" "Z3"] are equivalent.
The semantics is that the use-only list is first interpreted (if it's
empty, one starts with the current provers as the base), and only then
are the instructions of the include/exclude list applied to it, in
order.
There was already the special use-only instruction "ALL". Now, there is …
=> Added clean way to clear the list of current provers.

src/ecParser.mly, src/ecScope.ml, src/ecUtils.ml
The third stage of filtering in the definition of option_matching had
a bug, meaning that attempts to rely on it resulted in assertion failures.
But that last stage - disambiguating from right to left - was arguably
hard for users to predict, anyway. So, fixed the third stage, but
left it out of algorithm.
(If it's really desired, easy to put it back in, as now it'll
work. But do we really think users will understand why, e.g., [prover
x=1] means [prover maxlemmas=1] - because the x in maxlemmas comes
earlier when working backward as opposed to the x in maxprovers?)
This is how option disambiguation works: First filter-in those option
names having the letters of the abbreviation abv in the correct
order. Then work through the letters of abv in order, keeping
only those option names in …
=> Fixed bug in SMT option matching

Makefile
Only doubles the time taken by `examples` CI job (from 2.5 to 5 minutes). This is still less than the time it takes to check the standard theories, and could be reduced by some minor (but time-consuming) work on the mee-cbc proofs.
I chose this solution over the alternative of modifying the test specs in order to still allow separate checks locally.
We could also easily add a separate make target and job. I am not sure which would be preferred.
=> including mee-cbc in examples target

Makefile, src/ecProvers.ml, theories/algebra/StdRing.ec, theories/crypto/rom/PROM.ec, theories/distributions/DProd.ec, theories/encryption/Means.ec, theories/looping/FoldProc.eca, theories/looping/IterProc.eca
We can/should probably delete deploy-pruning-smt as we merge this.
=> Deploy smt blacklist

theories/analysis/RealExp.ec
Sorry if my interpretation is incorrect, dotp to me looks like a dot product.
One of its axioms captures an incorrect property that allows smt solvers to prove "false" quickly.
My best guess is that it introduces a contradiction along with other axioms.
PS: fixed the proof of CZ accordingly.
=> Critical bugfix on dot-product

default.nix
Without this, `nix-build` fails for me.
=> default.nix: adding installFlags

src/ecPrinting.ml
When printing instructions, a pp box was not closed.
=> Fixed unclosed box.

src/ecDecl.ml, src/ecDecl.mli, src/ecEnv.ml, src/ecHiGoal.ml, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecScope.ml, src/ecSection.ml, src/ecSmt.ml, src/ecSubst.ml, src/ecThCloning.ml, src/ecTheoryReplay.ml
I.e., with plain, axiomatized (including : {t | phi} as ax) and cases operators.
When cloning, [op nosmt x = ...] is allowed, but nosmt can't be used
with inlining mode.
Below are some examples:
```
(* example uses of nosmt on plain, axiomatized and cases operators *)
require import AllCore.
theory T.
op nosmt x : {int | 0 <= x} as ge0_x.
op nosmt x' : int = 3 axiomatized by x'_eq.
op z : int.  (* nosmt is not legal *)
op q : int.
axiom nosmt foo : z + q = 10.
op nosmt u = z + q.
lemma nosmt goo : u = 10.
proof.
(* smt fails *)
by rewrite /u foo.
qed.
end T.
print T.
(*
theory T.
op x : int.
axiom nosmt ge0_x: 0 <= T.x.
op x' : int.
axiom nosmt x'_eq: T.x' = 3.
op z : int.
op q : int.
axiom nosmt foo: T.z + T.q = 10.
op nosmt u : int = T.z + T.q.
lemma nosmt goo: T.u = 10.
end T.
*)
op …
```
=> Allows nosmt with all operators other than pure, abstract ones

src/ecTyping.ml, src/ecUtils.ml, src/ecUtils.mli
When a match has duplicate constructors but the same number of
branches as the number of constructors in the datatype being matched,
an exception was raised instead of the expected error message being
issued. Example:
```
type t = [A | B].
module M = {
proc f(x : t) = {
match x with
| A => { }
| A => { }
end;
}
}.
```
=> match with duplicate constructors can result in exception

src/ec.ml, src/ecOptions.ml, src/ecOptions.mli
Existing .eco cached results are used, but new ones are not generated.
@strub  Please review. Retrofitting the CLI processing to output an additional and mostly useless flag feels like a dirty hack I should have put more effort into.
=> Add a -no-eco option to disable .eco generation

theories/datatypes/FSet.ec
lemma disjointP (xs ys : 'a fset):
disjoint xs ys <=> forall (x : 'a), x \in xs => ! x \in ys.
=> Added disjoint xs ys as an abbreviation for xs `&` ys = fset0. Added

theories/algebra/Number.ec, theories/analysis/RealFLub.ec, theories/analysis/RealSeries.ec, theories/distributions/DList.ec, theories/distributions/Distr.ec, theories/distributions/SDist.ec
This is my draft for a new library about statistical distance, I'd be happy for comments and suggestions.
Some points:
- I renamed `summaleM` to `summableM_prod` and `summableM_dep` to `summableM_prod_dep` to free the name `summableM`. 
- There some lemmas in SDist that should go elsewhere but cause name clashes, in particular the reformulation of `dletE`. 
- What's a proper name for the lub/sup of a function, and which file should that go to?
=> Statisical distance and associated infrastructure

theories/distributions/DBool.ec, theories/distributions/DProd.ec, theories/distributions/Dfilter.ec, theories/distributions/Distr.ec, theories/distributions/SDist.ec
Once `mass d x = mu1 d x` is proved, `mass` and `mu1` can be used almost interchangeably. As lemmas about `mu` apply to the abbreviation `mu1` as well, this PR aims to replace `mass` by `mu1` wherever possible and remove lemma-duplication between the two.
=> Consistently use `mu1` instead of `mass`. 

scripts/docker/build-box/Dockerfile
The original base was 5 months out of date. An issue in the build was due to opam running as root.
The replacement base image is setup for opam to not run as root while allowing passwordless sudo.
This has been tested on some CI loops by building easycrypt with `make install`, but not yet using dune dev and `opam install easycrypt`.
=> [docker] Build box base is now an opam image

examples/ChaChaPoly/chacha_poly.ec, theories/crypto/PROM.ec, theories/crypto/ROM.eca, theories/modules/RndProd.eca
This pulls the LRO Oracle from the `FullEager` theory into the surrounding `FullRO` theory. Also, `LRO` is now part of `MkRO` as both share the same state. So cloning MkRO now also yields a fresh `LRO`.
=> lift LRO oracle out of FullEager

theories/crypto/PROM.ec
This is just a little lemma and small fix to remove an unnecessary assumption from `RO_FinRO_D` that I didn't have available at my point of use.
=> add lemma RO_LRO and generalize RO_FinRO_D

theories/distributions/SDist.ec, theories/encryption/DDH_hybrid.ec, theories/encryption/Hybrid.ec, theories/encryption/Indist.ec, theories/encryption/PKE_hybrid.ec
This PR extends `Hybrid` as follows:
- now statements using multiplication rather than division that also apply in the case where `q = 0`.
- documentation for the games that appear in the statements
In order to ensure that `HybGame` terminates even in the case where `q = 0`, the sampling is now done in `[0..max 0 (q-1)]` rather than [0..q-1].
=> allow zero queries in Hybrid 

easycrypt.opam, easycrypt.opam.template
This should fix the reporting of git commit hash on `git config` and on EasyCrypt startup.
=> [dune+opam] fix git hash versioning widget

theories/distributions/Distr.ec
When dealing with applications of dmap to list distributions I've had cases where the original ```dmap1E_can``` is too weak because it cares about the global properties of f and g instead of just what happens with values relating to x. Usually I'll know something about x to begin with (e.g. size is bounded by the length of the list).
If there's no stability reasons to keep the old version around I'd want to replace it instead since they are fairly similar.
=> stronger version of dmap1E_can

theories/algebra/IntDiv.ec
Added one lemma (`divzmul_divdiv`) stating that dividing by `a * b` is equivalent to first dividing by `a` and then dividing by `b` ( 'dividing' refers to 'perform euclidean division and take the quotient' here). Using this lemma, proved lemma `modz_pow2_div` that was `admitted` until now. Also, turned out one of the preconditions in `modz_pow2_div` (`0 <= i`) was not necessary, so I removed it.
=> Add lemma divzmul_divdiv and strenghten/proof modz_pow2_div.

theories/analysis/RealSeries.ec, theories/distributions/Distr.ec, theories/distributions/SDist.ec
This is a follow up a [discussion on Zulip](https://formosa-crypto.zulipchat.com/#narrow/stream/308381-EasyCrypt.3A-questions-.26-features/topic/turning.20subdistributions.20into.20distributions).
- add `dopt` which lifts a (sub)distribution on `'a` to `'a option`, assigning any remaining probability mass to `None`
- lemmas about summing sequences on option types
- proof that `dopt` preserves statistical distance.
Ultimately, I opted for defining `dopt` in terms of `mk` so as to not introduce a (spurious) dependency on `DBool` for the `dbiased` distribution.
=> dopt: extend subdistribution to lossless distributions on options

dune-project, src/phl/ecPhlFun.ml
Instead of introduce a single variable for the arguments tuple,
introduce all the procedure's arguments as single program variables.
Fix #166
=> [tactic]: [proc*]: fix procedure's arguments substitution

examples/ChaChaPoly/ske.ec, examples/MEE-CBC/CBC.eca, examples/br93.ec, examples/cramer-shoup/TCR.eca, examples/cramer-shoup/cramer_shoup.ec, examples/elgamal.ec, src/ecTyping.ml, src/ecTyping.mli, src/ecUserMessages.ml, theories/crypto/ROM.eca, theories/crypto/assumptions/DHIES.ec, theories/crypto/ske/CPA.eca
This has to be done in the semantic analysis pass, since local procedures cannot be distinguished from operators in parsing.
We could reject some more bad things in parsing, but doing it here gives us an easy and nice error message which will help users transition. (At least that's my excuse.)
=> Reject `x <- RHS` when `RHS` is a procedure call

theories/algebra/Bigop.eca, theories/datatypes/FSet.ec, theories/distributions/DInterval.ec, theories/distributions/Distr.ec, theories/prelude/Logic.ec
This PR adds a variety of lemmas that I found useful for developing the CV2EC theories.
The only changes (other than adding new lemmas) are:
- generalizing `reindex` to restict the cancellation property to the index list (possible source of minor incompatibility)
- resolving the FIXME in the proof of `fcardD1`
=> various small lemmas (Logic, FSet, Distr, DInterval, Bigop) 

README.md
The `depext` package fails to install with recent versions of opam.
The fix suggested in the package information is to use the renamed package `opam-depext`.
=> rename depext to opam-depext

src/ecCoreGoal.ml, src/ecCoreGoal.mli, src/ecHiGoal.ml, src/ecLowGoal.ml, src/ecLowGoal.mli
When having a conclusion of the form "forall x, E[x]", the
intro-pattern [#] was renaming `x` as `_`.
Internal: low-level intro tactic that returns the generated intro name
fix #221
=> Fix naming issue for the [#] intro-pattern

src/ecCoreModules.ml, src/ecCoreModules.mli, src/phl/ecPhlRnd.ml
The chosen ordering is the order of appearance as a left-value
in the program.
fix #220
=> Fix ordering of variables in `rndsem`

examples/ChaChaPoly/chacha_poly.ec, examples/ChaChaPoly/ske.ec, examples/PRG.ec, examples/Upto.ec, src/ecCoreFol.ml, src/ecCoreModules.ml, src/ecCoreModules.mli, src/ecEnv.ml, src/ecLowGoal.ml, src/ecModules.ml, src/ecModules.mli, src/ecPV.ml, src/ecPV.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecProofTerm.ml, src/ecTyping.ml, src/phl/ecPhlCall.ml, src/phl/ecPhlEqobs.ml, src/phl/ecPhlFun.ml, theories/crypto/MAC.ec, theories/crypto/PKS.ec, theories/crypto/SymmetricEncryption.ec, theories/query_counting/OracleBounds.ec
This is a breaking change.
This removes support for `proc *` tags in module types, which are currently causing soundness issues (see #206) and would benefit from being re-integrated later on as part of a more general and less trusted procedure annotation mechanism.
Formal developments that use `proc *`, or rely on `proc *` annotations in the standard library will need to update proofs.
Where the `proc *` annotation is in fact necessary for a result to hold (for example, when initial memories are different), it can be replaced with a hypothesis of the form `equiv [M.p ~ M.p: ={arg} ==> ={glob M, res}]` on the relevant procedures. In this case, instances of `sim` and `call (: true)` relevant to the procedure will need refined to take explicit account of the hypothesis.
Where the `proc *` …
=> [breaking] remove support for `proc *` tags in module types

src/ecScope.ml, theories/core/Bool.ec, theories/core/Core.ec, theories/crypto/PRP.eca, theories/datatypes/Int.ec, theories/datatypes/Real.ec, theories/prelude/Logic.ec, theories/prelude/Tactics.ec
This changes the semantics of `lemma ... by [].` to avoid hiding an unrestricted SMT call, and aligns `by []` with the `by done` semantics it has inside standard proof environments.
This is breaking: some proofs that went by SMT will now fail by `trivial`. The old behaviour can be recovered by replacing failing instances of `lemma ... by [].` with `lemma ... by smt.` However, we recommend avoiding the simple fix, and attempting to give more robust proofs to such lemmas.
=> [breaking] Unify meaning of `by []` in proofs and lemma declarations

theories/algebra/Matrix.eca
Add scalar-vector multiplication as part of the Matrix theory, as discussed on Zulip.
=> Add scalar-vector multiplication

theories/distributions/DBool.ec
Add a lemma to rewrite `dmap` onto a boolean predicate as a `dbiased`.
I encountered a need for the lemma through a particular use case of the `marginal_sampling` lemma from #239, and now I'm wondering if this lemma is general/reusable enough to belong in the standard library.
=> Relate `dbiased` and `dmap`

examples/PIR.ec, examples/PRG.ec, examples/vonNeumann.eca, src/phl/ecPhlWhile.ml, theories/distributions/Dexcepted.ec
This fixes #212 and implements a version of the pHL `while` rule which does have a(n unpublished) pen-and-paper proof.
This (obviously) makes using the pHL `while` rule generally less simple, but particularly so when the loop condition itself is probabilistically modified by the loop body (as, for example, in rejection sampling). Examples of proofs illustrating this case can be found in `theories/distributions/Dexcepted.ec` (starting line 299, including the `conseq`) and `examples/PIR.ec` (starting line 202, including also the `conseq`).
=> [breaking] fix unsoundness in pHL while rule

dune-project, easycrypt.opam, src/dune
This resolves the deprecation warning about the Stream module.
Fix #186
=> [build]: use camlp-streams

default.nix
Fix failing nix-shell build, as discussed on Zulip
=> Add camlp-streams dependency to nix build

theories/algebra/Ideal.ec
Change some `<-` to `<=` as discussed on Zulip
=> Allow quotient ring elements to be matrix entries

src/ecPV.mli, src/phl/ecPhlWhile.ml
The lower-bound should be independent from the variables written by the loop body.
=> [while (phl, >=)]: be more restrictive on the variant delta lower-bound

examples/UC/RndO.ec, src/ecLexer.mll, src/ecParser.mly, src/ecPrinting.ml, theories/core/CoreReal.ec, theories/datatypes/Real.ec
Postfix operators are named "(%x)" where x is a low-ident.
This generalizes the %r notation.
=> Add postfix notations.

examples/ChaChaPoly/chacha_poly.ec, theories/crypto/PROM.ec, theories/distributions/Mu_mem.ec, theories/newth/SmtMap.ec
This adds two new operators (`fsize` and `fcoll`) and a few lemmas to `SmtMap`. These are then used to bound the probability of collisions occurring when using the `ROmap` oracle from `PROM`. 
Note that the `Mu_mem` lemma for `fmap` uses a generalization of the `Mu_mem` lemmas for `fset`, which could also be applied to the latter. Input on this would be appreciated.
=> [stdlib] SmtMap lemmas, and bounding collisions for ROmap. 

theories/algebra/Ideal.ec
This is my contribution to fixing #280 . 
Note that I changed the statement of `eqvX` to restrict to nonnegative `n`. I'm not this even makes sense for negative `n`. Also, it's not used inside EC.
=> remove admits in Ideal.ec

theories/datatypes/List.ec
trivial proof by
rewrite assocTP  mem_map_fst.
but smt(assocTP mem_map_fst) fails.
=> added lemma assoc_none.

scripts/testing/runtest
The entry is `file_exclude`. It is a space-separated list of globs. A file is excluded if its basename matches any of the glob.
See `fnmatch.fnmatch` of the standard Python libraries to get a description of which glob patterns are supported.
Fix #303
=> [ec-runtest]: add the possibility to exclude file based on the name

src/ecTheoryReplay.ml
This resolves #154, but might require some more finesse.
In particular, perhaps we only want to force delta for top-level symbols?
=> force delta on convertibility checks

examples/plug-and-pray/Plug_and_Pray_example.ec, theories/datatypes/List.ec
There doesn't seem to be a ```max``` operator for lists yet. This implements that. I need it for defining the sup-norm.
=> operator to get maximal element in list

theories/datatypes/BitWord.eca, theories/datatypes/Word.eca
Added cancellation variant for ofword that uses mkseq to Word.eca, and added lemmas about the integer values of onew and zerow to BitWord.eca.
=> Additions to Word and BitWord: cancellation of ofword using mkseq, plus integer values of onew and zerow

src/ecHiInductive.ml, src/ecTypes.ml, src/ecTypes.mli, src/ecTyping.ml, src/ecTyping.mli, src/ecUserMessages.ml, theories/datatypes/List.ec
Termination is done via a simple subterm check on the last inductive argument.
Ref #62, #144
=> Implement a naive termination checker

.github/workflows/ci.yml, Makefile, default.nix, shell.nix
This PR:
- creates a `shell.nix` which more robustly presents the user with a shell ready for EasyCrypt development; (Although it currently lacks a default set of dev tools, they can be passed in as arguments.)
- improves the `default.nix` to better align with those used in nixpkgs and jasmin-lang;
- checks in CI that this `default.nix` successfully builds, also caching the resulting binary on cachix.
=> Improve nix local infra, test nix build in CI

theories/distributions/DBool.ec, theories/distributions/Distr.ec
This should be backward compatible, but the existing `dcond_supp` should be renamed to `supp_dcond`.
=> [theories]: lemmas for dcond and dbiased

default.nix, shell.nix
This makes it easier to bump versions and rely on CI.
In particular, it should facilitate the Why3 version bump awaiting in #352 and avoid temporary breakage one way or another as the corresponding version bump makes its way through to nixpkgs (https://github.com/NixOS/nixpkgs/pull/220986)
=> [nix] pin the Why3 version

src/ecPrinting.ml
Fix bugs in which formulas that end with with implications, conditionals or quantifiers and appear to the left of binary operators have their scopes extended to include those following binary operators. E.g.,
(3 :: 4 :: let x = 1 in [x]) = ys.
incorrectly pretty prints as
3 :: 4 :: let x = 1 in [x] = ys
This solution may be incomplete or not the best approach, but I haven't found any examples yet where it fails. close #348
=> An attempt at fixing pretty printing bugs in which formulas that end with low precedence prefix forms

src/ecPrinting.ml
Commit b2106aa6c3d89068a599a4037101b933bfb43804 suppressed  additional parentheses around `match ... end` in all circumstances, even though on the left and right of applications the parser requires parentheses, the theory being this makes it easier for humans to scan. So this commit inserts parentheses around matches in applications, but not elsewhere (e.g., not in infix operators). See below for examples. [The pretty printer needs a major redesign, so this is another stopgap measure.]
require import AllCore List. type t = [ A of int |  B of bool].
(* the following formulas now parse and pretty-print the same *)
lemma foo1 (f : int -> bool) :
f (match A 3 with | A a => a | B b => if b then 1 else 2 end).
proof. abort.
lemma foo2 :
(match A 3 with | A a => fun _ => a | B b => fun _ => 2 …
=> Fix to pretty-printing of matches in applications

src/ecCommands.ml, src/ecCoreLib.ml, src/ecCoreLib.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecProcSem.ml, src/ecProcSem.mli, src/ecScope.ml, src/ecScope.mli, theories/datatypes/Int.ec
computes the output distribution of a stateless proc.
The command is in beta-mode. It misses:
- a support for a larger set of instructions,
- better error messages,
- a registry of generated proc ops, and
- a hoare/phoare statement that links the operator to the procedure.
=> New command: proc op. This command generates an operator that

src/ecScope.ml
=> Forbid the usage of [declare] for concrete modules.

theories/analysis/RealFLub.ec, theories/analysis/RealLub.ec, theories/core/Core.ec, theories/datatypes/List.ec, theories/distributions/Distr.ec, theories/distributions/SDist.ec
This is the theory of `op p_max (d : 'a distr) = flub (mu1 d)` the maximal probability of atomic events in the distribution. 
This includes a proof that, despite the definition using `flub`, the maximum is always attained. This in turn required a few more lemmas on `flub` and factoring out the lemma:
```
lemma mu_pos_fin (d : 'a distr) eps : 
0%r < eps => is_finite (fun x => eps <= mu1 d x).
```
from the proof of `uniform_finite`. 
`p_max` implicitly captures min-entropy. I chose to not include the latter in this PR, because the PR is already quire big.
There's quite a few names and places (for lemmas) that I'm not sure about. Please review carefully.
=> [theories]: p_max (maximum probability for atomic events)

src/ecProvers.ml
This partially addresses #366 by emitting a warning on receiving `Invalid` results from an SMT solver, and allowing early failure when this happens.
The latter behaviour seems to have been intended, but subject to a race (which could potentially cause infinite looping) if two SMT solvers finished in the same iteration of the waiting loop and the first to be processed returned `Invalid` while the second returned `Valid`.
=> Warn and fail early on Invalid results from SMT

theories/datatypes/List.ec
This removes all unrefined `smt` calls from `List.ec` and significantly speeds up stdlib verification.
A deeper pass that removes unnecessary refined `smt()` calls would also be useful in the long run.
=> [lib] List: remove all raw smt calls

theories/crypto/ROM.eca
This strengthens the generic up to bad results on random oracles.
Any proof that was using the looser bound can be recovered easily with `smt().`
=> Tighten the ROM bad call results

src/dune, src/ec.ml
As part of an effort to create a language server for easycrypt, it would be handy to access the ocaml lib that is used to compile the easycrypt executable. 
This is done in this branch.
=> Turned the files in src into a lib called Core.

src/ecCoreFol.ml, src/ecCoreFol.mli, src/ecFol.ml, src/ecFol.mli
Instead, the f_subst mechanism should be used. (And this is in fact done for simplification of let formulas in EcReduction.)
=> Remove dead code relating to substitution

theories/datatypes/FSet.ec
Defining set product using list product make things easier to prove.
=> [theories] define `FSet` product using allpairs

theories/algebra/Bigop.eca, theories/crypto/assumptions/DHIES.ec, theories/crypto/prp_prf/Strong_RP_RF.eca
This removes more raw `smt` queries, which caused some core theories to last almost as long as the entire `make check` run. In theory, this should further speed up CI and local testing time both by allowing more parallelism and possibly by reducing the critical path.
Some of the longer running SMT calls may also have been causing erratic jumps in overall memory consumption that this may help bring under control. (This should not replace identifying runtime-related issues that cause those erratic jumps to compound and crash programs.)
=> [chore] remove more raw smt calls

theories/datatypes/FSet.ec, theories/datatypes/List.ec
These lemmas establish an equivalence between the unduped versions of two lists being permutations of each other and equality of the corresponding fsets. Combining these with the additional lemma on `perm_eq` and `undup` in `List.ec` seems to make the original `oflist_perm_eq` lemma redundant.
=> Additonal lemmas on fset (oflist) equality and a lemma on perm_eq/undup

theories/algebra/Ring.ec, theories/crypto/Birthday.ec, theories/crypto/PRP.eca, theories/crypto/assumptions/DHIES.ec, theories/crypto/prp_prf/Strong_RP_RF.eca, theories/datatypes/Real.ec, theories/distributions/Distr.ec, theories/query_counting/Counter.eca, theories/query_counting/OracleBounds.ec
I used the following regex on all the `.ec` and `.eca` files outside the examples folder: `(^|[^o])smt[^\(]*(\.|;|\(.*@.*\))`.
I left most the `smt(... @Theory ...)` invocations be for now.
I updated some of the invocations using old syntax that matched my regex as well.
=> Get rid of unbounded smt calls outside examples

examples/MEE-CBC/FunctionalSpec.ec, theories/datatypes/Word.eca
Previous `Word` implementation generates unprovable subtype-like axioms on `clone` and `proof*`. Directly including `Subtype` removes these proof obligations.
=> Propagate subtype changes to Word

default.nix, shell.nix, theories/distributions/DBool.ec
This reworks the nix configuration to:
1. avoid duplication of derivation information; and
2. pin provers to better support replication; (this is only partial: nixpkgs allows easy pinning of `z3` down to minor only, and `cvc4` is pinned only by virtue of no longer being maintained).
The pinning upgrades all provers to their maximum version supported by `why3` 1.6.0, stopping short of upgrading `cvc4` to `cvc5` due to clear instability in `cvc5` and its interactions with `why3` (50/50 chance of High failure). A minor refinement is needed in the case of one SMT call which fails with `z3` 4.12.2 and all other solvers, but succeeds with `z3` <= 4.12.1.
The pinning of `alt-ergo` to 2.4.2 works, but leaves paths and derivation names unchanged, so `alt-ergo-2.4.2` appears in paths as …
=> [nix] Rework the nix configuration

examples/MEE-CBC/CBC.eca, theories/crypto/Birthday.eca, theories/crypto/PRP.eca, theories/crypto/prp_prf/Strong_RP_RF.eca, theories/distributions/Distr.ec
I'd also like to add `exists_max` to `Distr.ec` instead but the file does not pass the check on my computer, most likely because I don't have CVC4 installed (M1 Mac).
I've also made the theory abstract due to the uninstantiated `T` parameter. This is needed because the modules cannot take type parameters.
Thanks to @Cimylog for finding this.
=> get rid of axiom and uninstantiated operator in `Birthday`

src/ecCoreFol.ml, src/ecCoreFol.mli, src/ecDecl.ml, src/ecDecl.mli, src/ecEnv.ml, src/ecFol.ml, src/ecHiGoal.ml, src/ecInductive.ml, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecReduction.ml, src/ecScope.ml, src/ecSection.ml, src/ecSmt.ml, src/ecSubst.ml, src/ecThCloning.ml, src/ecThCloning.mli, src/ecTheoryReplay.ml, src/ecUserMessages.ml, theories/algebra/Ideal.ec
When cloning a theory, inlined operator definitions must be expressions s.t. their substitution can be done in procedures bodies.
=> Operators body can now be formulas

src/phl/ecPhlRCond.ml
=> Fix error when typing a constructor in a direct matching.

Makefile, config/tests.config, scripts/testing/runtest, src/ec.ml
This argument tells `runtest` which binary to use for EasyCrypt.
It takes precedence over what is found in the INI file (in default/bin).
Moreover, `easycrypt runtest` automatically set --bin to itself. This allows to select the correct version of EasyCrypt without having to tweak the INI file accordingly.
=> [runtest]: new CLI argument --bin

src/ecCallbyValue.ml, src/ecDecl.ml, src/ecDecl.mli, src/ecEnv.ml, src/ecEnv.mli, src/ecHiGoal.ml, src/ecLowGoal.ml, src/ecLowGoal.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecReduction.ml, src/ecReduction.mli, src/ecScope.ml, src/ecSection.ml, src/ecSubst.ml, src/ecTheoryReplay.ml, src/phl/ecPhlConseq.ml, src/phl/ecPhlSkip.ml
Operator unfolding when applied to enough arguments
When declaring an operator, it is now possible to specify which
arguments are mandatory before an operator application is
automtically unfolded during simplification.
Syntax is:
```
op name (x1 : t1) (xp : tp) / (x_p+1 : t_p+1) ... = ...
```
where the optional `/` indicated that the operator `name` will
be automatically unfolded when applied to at least `p`
arguments.
=> Operator unfolding when applied to enough arguments

default.nix, scripts/nix/LICENSE, scripts/nix/alt-ergo/default.nix, scripts/nix/cvc4/cvc4-bash-patsub-replacement.patch, scripts/nix/cvc4/default.nix, scripts/nix/cvc4/minisat-fenv.patch, scripts/nix/cvc5/default.nix, scripts/nix/z3/default.nix
This vendors derivations for provers known to work with our pinned why3, independently of updates to nixpkgs—allowing us to move ahead if we decide to stick to an LTS or to stay behind if we keep in line with `unstable`.
This should improve reproducibility of external checks we run, and of checks run externally.
=> [nix] vendor prover derivations

src/ecTheoryReplay.ml
The check should use the full conversion.
fix #437
=> cloning: fix regression bug in operators convertibilty check

src/ecOptions.ml
Library paths can be specified using the environment variable ECPATH. It contains a list of “idirs” separated by semicolumns (;).
Each “idir” is a path, optionally qualified (when present, the qualifier is followed by a colon (:)).
Open questions / bikesheding:
- name of the environment variable
- syntax (e.g, use of `;` as separator)
- what about `rdirs`?
=> Read idirs from the ECPATH environment variable

src/ecCallbyValue.ml, src/ecCoreFol.ml, src/ecCoreFol.mli, src/ecCoreModules.ml, src/ecEnv.ml, src/ecEnv.mli, src/ecFol.ml, src/ecFol.mli, src/ecLowGoal.ml, src/ecLowGoal.mli, src/ecLowPhlGoal.ml, src/ecMatching.ml, src/ecMatching.mli, src/ecPV.ml, src/ecPath.ml, src/ecPath.mli, src/ecPrinting.ml, src/ecProofTerm.ml, src/ecReduction.ml, src/ecSection.ml, src/ecSmt.ml, src/ecSubst.ml, src/ecTypes.ml, src/ecTypes.mli, src/ecTyping.ml, src/ecUnify.ml, src/ecUserMessages.ml, src/phl/ecPhlConseq.ml, src/phl/ecPhlDeno.ml, src/phl/ecPhlExists.ml
This fixes #102 through eager normalization of module globs at typing and instantiation time.
=> [internal] Fix glob unsoundness

src/ec.ml, src/ecOptions.ml, src/ecOptions.mli
EasyCrypt now reads project-local files for getting its configuration settings. This configuration file takes precedence over the system-level configuration file.
The project-local configuration file is named 'easycrypt.project'.  It is identical to the system-level configuration file.
When compiling a file, the configuration file is searched upward from the target file directory. When ran in interactive mode, the configuration file is searched upward from the current working directory.
Note that when ProofGeneral starts EasyCrypt, the working directory is set to the directory of the focused file.
=> Support project-local ini files

src/ecOptions.ml, src/ecOptions.mli
The configuration key is "timeout"
=> SMT timeout can now be configured in INI files

src/ecCoreFol.ml, src/ecMemory.ml
These are unused after the EcAst changes. Are they planned to be used?
=> Removed two unused type declarations.

Makefile, src/ec.ml, src/ecProvers.ml, src/ecProvers.mli
Syntax is name@version. The selected prover is the prover with name `name` and with the lowest version that is greater (or equal) than `version`.
For example, if Z3 4.8.0, Z3 4.8.2 & Z3 4.12.2 are installed, Z3@4.8 selects Z3 4.8.0.
=> Allows selecting a prover by its version number.

.github/workflows/ci.yml, scripts/testing/runtest, src/ec.ml, src/ecOptions.ml, src/ecOptions.mli
This allows to temporarily fix the Jasmin CI.
=> runtest: allows to specify provers from the CLI

Makefile, src/ecPrinting.ml, src/phl/ecPhlConseq.ml
Until now, `make` was building EasyCrypt in release mode.
The set of warning flags in release mode is weaker then in development mode. Switching to dev mode caused the apparition of some warnings. This commit fixes them.
=> Compile in `dev` mode by default.

src/ecTypes.ml
This map is allowed to do name capture and is hence sensitive to bound variables renaming.
=> In substitutions, lazyly refresh the codomain of the univar map

src/ecHiTacticals.ml, src/ecLexer.mll, src/ecParser.mly, src/ecParsetree.ml, src/phl/ecPhlCodeTx.ml, src/phl/ecPhlCodeTx.mli, theories/distributions/Dexcepted.ec
This tactic allows to weaken the memory of a phoare hypothesis by adding new variables to it.
This tactic is needed in the while rule for phoare, when one wants to apply the induction hypothesis & the memories are not compatible. Currently, the convertibility check does not enforce that memories are equal, but a to-come PR is going to fix that point.
=> Add tactic `weakmem`

src/ecCoreFol.ml, src/ecHiTacticals.ml, src/ecProofTyping.ml, src/ecProofTyping.mli, src/phl/ecPhlApp.ml, src/phl/ecPhlHiCond.ml, src/phl/ecPhlRCond.ml, src/phl/ecPhlRnd.ml, src/phl/ecPhlWhile.ml, src/phl/ecPhlWp.ml
This family of functions type-check a formula w.r.t. a memory that is infered from the program logic goal.
The commit changes two things:
- for prhl, its uses the same memory name as the one used in the program logic goal. (Previously, it was using `mhr`)
- its returns the memory that has been used for the type-checking
=> Internal API: process_Xhl_*

default.nix
EasyCrypt compiles with the last version of Why3.
=> nix-shell: remove why3 pin

Makefile
This is not yet to be merged even if CI goes through—we should consider effect on CI time.
CVC5 seems robust enough now that `make check` reliably succeeds (and does so without warning) on my machine.
=> Bump provers to latest that succeeds, drop CVC4

scripts/docker/base-box/Dockerfile
This PR should not be accepted before we carefully checked that we do not have any penalty in using OCaml 5.x.
The published Docker image is currently based on this PR.
=> Docker: bump OCaml to 5.1.0

src/ecCoreModules.ml, src/ecCoreModules.mli, src/ecHiTacticals.ml, src/ecLexer.mll, src/ecParser.mly, src/ecParsetree.ml, src/ecUnifyProc.ml, src/ecUnifyProc.mli, src/phl/ecPhlOutline.ml, src/phl/ecPhlOutline.mli, tests/outline.ec
The main idea is to provide an inverse to `inline` when proving an equiv.
Currently, it supports basic procedure unification that requires manual selection of the program slice to unify with, as well as, requiring near exact matches on program structure. An optional return value can be supplied for situations where the return expression is just a program variable and needs to be renamed/deconstructed.
There is also support for statement outlining although, this is more of a `transitivity *` with program slicing so may require change. 
Syntax and variants: 
- Procedure outlining: `outline {m} [s - e] M.foo` or `outline {m} [s - e] M.foo @ lv`
- Statement outlining: `outline {m} [s - e] { s1; s2; ... }`
_m_: 1 or 2
_s_,_e_: code position
_M.foo_: path to procedure
_lv_: a left-value
when …
=> [tactic] outline

src/ecParser.mly, src/ecParsetree.ml, src/ecThCloning.ml, src/ecThCloning.mli, src/ecUserMessages.ml
As a fix for #380, disallow all ways of overriding a module when cloning a theory.
Note: this will most likely break some existing proofs.
=> Remove module overriding

src/ecEnv.ml, src/ecEnv.mli, src/ecPath.ml, src/ecPath.mli, src/ecPrinting.ml
The printer now does a eager filtering of notations (only notations that share the same head symbol as the printed formula are considered)
The does not change the behavior of the pretty-printer, but greatly improves performance.
=> Optimize pretty-printing of notations

examples/WF-examp.ec, theories/structure/WF.ec
Added example usage of WF.ec, plus various cleanups, including standardizing terminology. (Name changes only on internal operator and lemma.)
=> WF cleanup + example

src/ecCallbyValue.ml, src/ecHiGoal.ml
Before this commit, `simplify` was not configured to unfold symbols marked for auto-unfolding.
=> Unify the behavior of simplify & /= w.r.t. auto-unfolding.

src/ecHiTacticals.ml, src/ecParser.mly, src/ecParsetree.ml, src/phl/ecPhlRewrite.ml, src/phl/ecPhlRewrite.mli, tests/procchange.ec
This tactic allows to change an expression in a statement by some other expression. When applied, the user has to prove that the two expressions are equal (generalizing over all the program variables)
This tactic applies to any program logic.
The syntax is:
proc change <side?> <codepos> : <form>
This tactic is in the TCB.
Test plan:
- unit test (tests/prochange.ec)
=> New tactic: "proc change"

.github/workflows/ci.yml, Makefile, scripts/testing/runtest, src/ec.ml, src/ecOptions.ml, src/ecOptions.mli
=> runtest: accept all options from the prover/loader group

src/ecHiTacticals.ml, src/ecLowGoal.ml, src/ecMatching.ml, src/ecMatching.mli, src/ecParser.mly, src/ecParsetree.ml, src/phl/ecPhlRewrite.ml, src/phl/ecPhlRewrite.mli, tests/procrewrite.ec
This tactic allows to rewrite an expression in a statement.
The syntax is:
```
proc rewrite <side?> <codepos> <proof-term>
````
This tactic relies on "proc change" and does not modify the TCB.
Test plan:
- unit test (tests/procrewrite.ec)
=> New tactic: "proc rewrite"

src/ecHiGoal.ml, src/ecParser.mly, tests/rw_explicit_eq_with_pattern.ec
It is now possible to use pattern variables in cut-rewrite:
```
rewrite (_ : pattern = term)
```
See tests/rw_explicit_eq_with_pattern.ec for examples.
=> Allow patterns in cut-rewrite.

.github/workflows/ci.yml, .github/workflows/external.json
This adds support for external proof repos hosted off github to the existing (simple) external CI infrastructure, and uses SHA3 as a CI test.
The immediate ambition is to add all external proofs that should check with `main` (XSalsa, CryptoBox, XMSS, ...) to checks for PRs onto `main` (not for arbitrary commits; the restriction still needs added). This will then enable the developers of feature branches (`deploy-expected-cost`, `deploy-qrom`) to activate external CI for the external proofs they support.
=> Extend external CI to support non-github repos

src/ecMatching.ml, src/ecProofTerm.ml
HO matching was sometimes wrongly triggered
=> Fix HO matching

.github/workflows/external.json
Places the next branch of the cryptobox proof into the external CI.
This PR is meant to also try to figure out what is a good process to impose on external CI contributions.
=> External CI: add cryptobox

.github/workflows/external.json
Add the XSalsa20 security proof (and general proof for PRF cascades) to the external CI.
=> [external ci] add xsalsa security

src/ecCoreSubst.ml
When crossing a let-binding, remove the bound variables from the substitution in *all* situation.
Fix #544
=> [subst]: fix name capture

src/ec.ml, src/ecOptions.ml, src/ecOptions.mli
For that purpose, a new CLI argument (-jobs) has been added to the `runtest` command.
=> runtest: all to control the number of files checked in parallel

theories/prelude/Logic.ec
Remove an extraneous `axiom` by filling in the proof.
=> Change `axiom eq_choice` to lemma

src/ecCommands.ml, src/ecCommands.mli, src/ecHiGoal.ml, src/ecHiGoal.mli, src/ecHiTacticals.ml, src/ecLexer.mll, src/ecLowGoal.ml, src/ecLowGoal.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecScope.ml, src/ecScope.mli, theories/query_counting/OracleBounds.ec
Non-strict proof-mode allows SMT failures to be catchable with `try` and affiliated. This tends to lead to hardly maintainable proofs and is not used anymore.
The commits remove the internal handling of non-strict proof scripts, removing the `proof strict` / `proof -strict` syntax.
The only leftover is the `try!` tactical that allows to catch SMT failures. It is useful for debugging purpose but should not remain in final scripts.
=> Remove non-strict proof mode.

src/ecReduction.ml, tests/reduction-record-eqyality.ec
The reduction follows the current behavior for tuples.
Closes #551
=> Reduce equalities between record literals.

.github/workflows/external.json
ML-KEM is hard-failing on Github Actions for an obscure reason.
Moreover, ML-KEM checking time, even in weak-check mode, is uterly long to check.
While it is investigate & ML-KEM proofs are updated using the map-reduce tactics, I am removing it from the CI.
It will be reintegrated ASAP.
=> [ci]: remove ML-KEM

.github/workflows/ci.yml
This slows down the CI and brings little benefits.
=> [ci]: do not update opam

src/ecCommands.ml, src/ecCommands.mli, src/ecScope.ml, src/ecScope.mli
Added minimal external API, faciliating the development of tools using EasyCrypt as a library. The changes are limited to ecScope.{ml,mli} and ecCommands.{ml,mli} are are labeled "external API" as otherwise they might be removed as dead code. (Based on the API developed at part of the UC DSL implementation, but names have been made generic.)
=> Added minimal external API

src/ecEnv.ml, src/ecPath.ml, src/ecPath.mli, src/ecTheoryReplay.ml, src/ecTyping.ml
The bug takes its root in a poorly document API (EcPath.isprefix).
The function now takes named arguments to make things clearer.
fix #570
=> [internal]: fix filtering as saved theory-related environments

examples/ChaChaPoly/chacha_poly.ec, src/ec.ml, src/ecProvers.ml, src/ecProvers.mli, theories/distributions/DInterval.ec
Why3 can define several variants (e.g. counterexamples, noBV).
Currently, EasyCrypt select the first variant that comes in the prover list. From now on, the default variant (= empty name) is selected by default. It is also possible to provide the desired in the prover name (syntax = "prover[variant]", e.g. "Z3[noBV]").
This is compatible with the version selection (e.g. "Z3[noBV]@4.8")
=> [smt]: proper selection of SMT variant

src/ecTheoryReplay.ml
The conversion check has a strategy to unfold the LHS before the RHS when checking that two maybe applied different operators are convertible. When cloning a theory with the "theory T <- U" stanza, the RHS of the conversion is an alias to the RHS. By swapping the two arguments, the convertibility check is immediate, while on the other case, both hands will be normalized.
A proper way to solve this problem would be to have a more advanced unfold heuristic (by using a generation ID per operators or having more meta-information on the operators bodies)
=> Optimization hack for checking operator compatibility in clones

.github/workflows/ci.yml
This is a hack-ish (? perhaps it's normal, I don't know) way of selecting which branch of a proof repository should be used when running external CI checks. The external CI configuration is used as a default branch to check. However, when running in EasyCrypt branch `X` (or in a PR related to EasyCrypt branch `X`), the external CI check will run in the proof repository's branch `merge-X` if it exists, only checking the default branch if `merge-X` does not exist.
This, combined with some light scripting on the proof repository side of things, then supports the following workflow, meant to engage when we make breaking changes to EasyCrypt:
1. We open a PR from branch `X` introducing a breaking change;
2. External CI checks predictably fail, and we notify maintainers and guide proof fixes; …
=> external CI checks for PR-specific branch

src/ecCoreGoal.ml, src/ecCoreGoal.mli, src/ecHiGoal.ml, src/ecHiGoal.mli, src/ecHiTacticals.ml, src/ecLowGoal.ml, src/ecLowGoal.mli, src/ecMaps.ml, src/ecParser.mly, src/ecParsetree.ml, src/ecProofTerm.ml, src/ecScope.ml, tests/done_in_proofterm.ec
Simple tactics (//, //#, /#) can now been used in proof-terms.
=> Simple tactics in proof-terms.

.github/workflows/ci.yml
We need to check existence of a remote branch with refs/heads (otherwise, we would accept partial matches), but checkout without.
This should be checked by creating and pushing a branch `merge-fix-diversified-external-ci` in one of our external repositories, rather than just accepting the first set of CI results.
=> [ci] diversified external CI selects a valid branch

theories/datatypes/FMap.ec
This is to stage the renaming in #605 across a release.
- Pre-release: add `FMap` as an alias for `SmtMap`.
- Post-release: deprecate `SmtMap` by merging #605.
=> stage the SmtMap -> FMap renaming

examples/ChaChaPoly/chacha_poly.ec, examples/cramer-shoup/cramer_shoup.ec, examples/plug-and-pray/Plug_and_Pray_example.ec, src/ecCommands.ml, src/ecEnv.ml, src/ecEnv.mli, theories/crypto/RndExcept.eca, theories/crypto/assumptions/DHIES.ec, theories/crypto/assumptions/PKSMK.ec, theories/encryption/Hybrid.ec, theories/encryption/Indist.ec
Before, the globals compoenents were sorted by the hash-consing
tags, leading to a 1. unpredictable ordering & 2. unstable
ordering (especially in case of undos/redos)
Globs components are now sorted by fullnames.
=> internal: stable ordering of globals components

scripts/testing/runtest
=> runtest: properly restore the terminal on (exceptional) exit

src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecTyping.ml
Currently, when resolving an identifier, EasyCrypt tries to resolve it as a logical variable first, and then as a program variable (in the active memory), even when a memory specifier is given.
This commit adds a new memory specifier that changes the resolution order: when using it, we first try to resolve the identifier as a program variable (in the given memory), and then as a logical variable if no program variable matching that name is found.
The syntax is `form{!memory}`.
The pretty-printer has been updated accordingly.
Fix #122, fix #196
=> Fix logical variable shadowing program variables

src/ecEnv.ml, src/ecEnv.mli
The environment module is currently pre-normalizin module aliases in lemmas & operators. This legacy code was a work-around w.r.t. the glob unsoundness.
This behavior is now useless and kills the benefit of module aliases. This commit removes it.
=> stop normalizing lemmas/operators w.r.t. module aliases

.github/workflows/ci.yml
This allows to remove the job duplicates detection script that has its own odities and was badly working with automatic merges.
If ones want to have the CI running on its develoment branch, that person should create a draft PR.
=> CI: only for PR & main

src/ecCoreFol.ml, src/ecCoreFol.mli, src/ecCoreLib.ml, src/ecCoreLib.mli, src/ecTypes.ml, src/ecTypes.mli
This adds bindings for the List theory in src/ecCoreLib.ml, form constructors for them in src/ecCoreFol.ml and a constructor for the list type in src/ecTypes.ml
=> PR: Adding CoreLib bindings for List theory

src/ecHiGoal.ml
=> Allow generalizing memories

src/ecHiGoal.ml
If not, unfolding an high-order operator will produce a formula that is not convertible to the original one.
fix #590
=> internal: allow eta reduction when checking the unfolding of an operator

src/ecAst.ml, src/ecCoreModules.ml, src/ecCoreModules.mli, src/ecPV.ml, src/ecPV.mli, src/ecParser.mly, src/ecUtils.ml, src/ecUtils.mli, src/phl/ecPhlCodeTx.ml, tests/cfold.ec
This new version of constant-propagation doesn't stop after the propagation. Instead, it continues as far as possible.
The tactic takes as argument a limit `n`. In that case, the constant propagation will only be applied for the first `n` lines of the program.
=> Improve constant-propagation

src/ecParser.mly, src/ecParsetree.ml, src/phl/ecPhlRewrite.ml, src/phl/ecPhlRewrite.mli, tests/procrewrite-simpl.ec
The implementation is outside of the TCB.
=> `proc rewrite` now supports the `/=` rule

src/ecCorePrinting.ml, src/ecHiTacticals.ml, src/ecMatching.ml, src/ecMatching.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/phl/ecPhlSwap.ml, src/phl/ecPhlSwap.mli, theories/distributions/DJoin.ec
Moreover, offsets can bow be absolute (i.e. can be a code-position). In that case, the meaning is "move the code block before the targetted instruction".
This work brings some breaking changes:
- the variant `swap i1 i2 i3` has been removed. It was a way to give a direct access to the low-level functionality, but its interface is brittle and is not used by any development
- a bug has been found in the resolution of negative code position (they were all shifted by one, making impossible to target the last instruction). This now has been fixed.
=> The tactic `swap` now takes generalized code position.

src/ecIo.ml
A conflict arises with code positioning and decimal numbers (e.g., 2.2). To address this, the incremental API of Menhir is now employed. When the lexer identifies a decimal number, but the parser is in a state where a decimal number isn't accepted, it returns the a number-dot-number token sequence instead.
=> lexer: do not lex decimal numbers when the parser won't accept them

src/ecCorePrinting.ml, src/ecMatching.ml, src/ecMatching.mli, src/ecPrinting.ml, src/phl/ecPhlLoopTx.ml
Keep a resolved version of the position so that it can be safely reused later.
=> fix "unroll for" failure (InvalidCPos)

src/ecMatching.ml, src/ecMatching.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecTyping.ml, src/phl/ecPhlInline.ml, tests/match_codepos.ec
- `^match` pattern now allowed within a code pos
- `#cname` can be used to select the appropriate sub-branch of a match
- `^lv<@` and `^lv<$` are now permited
=> Improve code positions (match + extended assignments)

src/ecLoader.ml
The duplicate path check now accounts for the associated namespace, allowing the same path to be added to multiple different namespaces.
=> Fix include-path management regarding duplicate paths

src/phl/ecPhlEqobs.ml
=> Track more precisely tuple to tuple assignments in sim

README.md
The original text was using both the fenced markers (```) and the spacing to give the instructions for NIX.
=> Fixing code blocks display in readme

examples/MEE-CBC/FunctionalSpec.ec, theories/algebra/Group.ec, theories/algebra/IntDiv.ec, theories/crypto/assumptions/DHIES.ec, theories/datatypes/Array.ec, theories/datatypes/FMap.ec, theories/datatypes/FSet.ec, theories/datatypes/Word.eca, theories/distributions/DList.ec, theories/distributions/Distr.ec, theories/prelude/Logic.ec
Note that this does not fully deprecate `axiomatized by` yet. It only removes its uses from the stdlib.
Ref: #94
=> get rid of `axiomatized by` in favor of `[opaque]` with trivial lemma

src/ecHiInductive.ml, src/ecPrinting.ml, src/ecScope.ml, src/ecTyping.ml, src/ecUnify.ml, src/ecUnify.mli, tests/overloading.ec
This PR is about using more type information to resolve the overloading of operators. Currently, the following is now accepted:
```
require import AllCore List.
theory T.
op o : int.
op a : int -> int -> int.
end T.
theory U.
op o : bool.
op a : bool -> bool -> bool.
end U.
import T U.
op foo : int -> unit.
op bar = foo o.
op plop1 = foldr a false [].
op plop2 = foldr (fun x => a x) false [].
op plop3 = foldr (fun x y => a x y) false [].
```
=> Better operators overloading inference

examples/br93.ec, src/ecLowPhlGoal.ml, src/ecMatching.ml, src/ecMatching.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecTyping.ml, src/ecTyping.mli, src/ecUserMessages.ml, tests/fine-grained-module-defs.ec
The goal of this PR is to introduce a new mechanism that permits the user to create a new module by slightly tweaking an existing module definition.
At present the draft has the following features:
- Introduce new module variables.
- Introduce new local variables.
- Delete/Modify/Add statements at particular code positions
- Delete branches (match support is not currently working fully)
- Modify branch conditions
- Insert new branches around a chunk of code
- Modify the return expression
Syntax (needs work) :
```
module N = M with {
var x : t (* add new module variable *)
proc f [
var y  : s (* add new local variable *)
cp +/-/~ { s } (* insert after/insert before/modify a statement *)
cp -  (* delete a statement *)
cp + ( e ) (* insert new if statement with condition `e` surrounding the …
```
=> Fine Grained Module Definitions

src/ecTyping.mli
This is so external tools can check types, forbidding type variables.
=> Exposed the tp_nothing typolicy of EcTyping

scripts/testing/runtest
=> runtest: ignore Emacs lock files (.#XXX)

src/ecCommands.ml, src/ecCorePrinting.ml, src/ecEnv.ml, src/ecEnv.mli, src/ecMaps.ml, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecScope.ml
This commit introduces the following printing commands:
- `print hint`: prints all hints in the current scope
- `print hint simplify`:  same but only for simplify hints
- `print hint solve`: same but only for solve hints
- `print hint rewrite`: same but only for rewrite hints
=> Better printing of hint DBs

src/ecCommands.ml, src/ecEnv.ml, src/ecEnv.mli, src/ecLowGoal.ml, src/ecLowGoal.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecScope.ml, src/ecSection.ml, src/ecSubst.ml, src/ecTheory.ml, src/ecTheory.mli, src/ecTheoryReplay.ml, tests/hint_rigid_should_fail_immediate.ec
Add functionality to disable reduction of the expressions in hint solve/exact.
=> Rigid unification option for `hint solve/exact`

theories/datatypes/FMap.ec
Simple lemmas that are missing for some reason.
=> FMap: add lemmas on range after update

theories/crypto/PublicKeyEncryption.eca, theories/crypto/PublicKeyEncryptionROM.eca
Analogous to KEM libraries (see https://github.com/EasyCrypt/easycrypt/pull/672) but for PKE schemes. Main difference being that there is no theory with basic relations/properties in standard model theory here. Feedback from discussion on KEM libraries already incorporated.
=> Add PKE libraries (both standard model and ROM)

theories/crypto/KeyEncapsulationMechanisms.eca, theories/crypto/KeyEncapsulationMechanismsROM.eca
Initial attempt at libraries for KEM (both in standard model and ROM).
There are several points of interest/discussion listed below which I think should be agreed upon before merging.
The resulting conclusions for these discussion points will directly translate to several other libraries I have coming up, meaning the merging of them will be smoother.
Points of Interest/Discussion (standard model):
- Currently, the module type for (CCA) oracles is a functor type (taking a scheme module as parameter). I feel like this is not necessarily ideal, because one might want to have an oracle that does not directly use the scheme sometimes (but, e.g., only parts of its code). To achieve this with the current functor type, one would need to create oracles that take a scheme but don't use it, which …
=> KEM libraries (non-ROM and ROM)

.github/workflows/external.json
The external CI is currently configured to use the `master` branch of the XSalsa repo, which follows the latest EC release instead of EasyCrypt's `main`. This points the external CI to the correct branch.
=> [external CI] use dev branch for XSalsa checks

examples/ChaChaPoly/chacha_poly.ec, src/phl/ecPhlOutline.ml, src/phl/ecPhlOutline.mli, src/phl/ecPhlRwEquiv.ml, src/phl/ecPhlTrans.ml, src/phl/ecPhlTrans.mli, theories/crypto/PROM.ec
This uses from previous work from the outline tactic to automatically discharge the first two goals when doing a `transitivity*` or `replace*`.
=> Improve transitivity* and replace*

src/ecTheoryReplay.ml
=> Apply cloning substitution to datatype ctor types

src/ecMatching.ml, src/ecMatching.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecTyping.ml, tests/codepos-tuple-name.ec
E.G. `^(x)<-`, `^(y)<-`, `^(z)<-` will all match on `(x, y, z) <- e`
=> New code-position variants: ^()<-, and ^(x)<- to match tuples.

examples/ChaChaPoly/chacha_poly.ec, examples/MEE-CBC/FunctionalSpec.ec, examples/ehoare/adversary.ec, src/ecCommands.ml, src/ecCoreLib.ml, src/ecLexer.mll, src/ecParser.mly, src/ecParsetree.ml, src/ecScope.ml, src/ecScope.mli, src/ecThCloning.ml, src/ecThCloning.mli, src/ecTheoryReplay.ml, tests/subtype-clone-sugar.ec, theories/algebra/Poly.ec, theories/algebra/ZModP.ec, theories/datatypes/Word.eca, theories/datatypes/Xreal.ec, theories/structure/Quotient.ec, theories/structure/Subtype.eca
Current `Subtype` theory forces to have a type `sT` for the subtype carrier. This PR is to revert this (i.e. the subtype carrier can be substituted by a user type) but add a command to carefully clone it.
=> revert subtype theory + syntactic sugar for cloning it

theories/datatypes/List.ec
I needed some of these lemmas for a recent project and thought I would add them + try to shorten other proofs using them where possible.
The main result here that is useful to me is the `uniq_le_perm_eq` lemma, which seems to encompass the other lemmas that are there currently, provided you also have the `perm_eq_uniq_impl` lemma. I know that these are derivable from the present lemmas, but this is not directly obvious (at least it wasn't to me). And I would say this is especially so since the lemma that currently comes closest to `uniq_le_perm_eq`, which is `uniq_perm_eq_size`, uses more and stronger hypotheses than necessary (see the new proof, which clears one of the hypotheses and does not much more than directly applying a lemma with weaker hypothesis).
The other, smaller lemmas on …
=> Add list lemmas and shorten some other proofs using them

src/ecHiGoal.ml, src/ecHiGoal.mli, src/ecParser.mly, src/ecParsetree.ml, tests/clear.ec
This feature was requested at the retreat.
Please have patience with the review. This is literally the first OCaml code I've ever written.
=> Extend `clear` tactic to allow clearing *all* unused items in the context recursively

theories/crypto/KeyEncapsulationMechanisms.eca, theories/crypto/PublicKeyEncryption.eca
Copy-paste mistakes I forgot to fix before
=> Fix return of properties with provided bit in KEM/PKE libraries

src/ecParser.mly, src/ecParsetree.ml, src/ecTyping.ml, tests/fine-grained-module-defs.ec
- Allow for code position ranges to specify blocks of changes.
+ `[cp .. cp]` specify a block using two code positions.
+ `[cp - cp1]` specify a block using an initial position and another position relative to it.
- Minor change to syntax for adding above a statement ( `+ ^`).
- Allow for removing a module variable.
=> Improvements to module tweaks

src/ecPV.ml, src/phl/ecPhlEqobs.ml
- handle M.f(x, y) vs M.f((x, y)) cases
- allow matching local operators
=> Minor fixes for sim

src/ecHiGoal.ml
When overriding an axiom or lemma, ensure that any errors trigger a user message rather than letting the kernel raising a low-level error.
=> Hi-level error message in clone (axiom <-)

examples/MEE-CBC/CBC.eca, src/ecMatching.ml, src/ecParser.mly, src/ecParsetree.ml, src/ecProofTyping.ml, src/ecProofTyping.mli, src/ecTyping.mli, src/ecUnifyProc.ml, src/ecUnifyProc.mli, src/phl/ecPhlOutline.ml, src/phl/ecPhlOutline.mli, tests/outline.ec, theories/crypto/PRP.eca, theories/crypto/ROM.eca, theories/crypto/SplitRO.ec, theories/crypto/assumptions/DHIES.ec, theories/crypto/prp_prf/Strong_RP_RF.eca, theories/distributions/DList.ec, theories/distributions/SDist.ec, theories/looping/FoldProc.eca, theories/looping/IterProc.eca, theories/modules/RndProd.eca
A few changes:
- Replaced explicit left values with a more general *alias* mode. This should be used to prevent undue capture of program variables by the outlined function.
- Tweaked unification procedure to catch type mismatches.
- Code position ranges can now be used.
- Minor updates to error messages and syntax.
- Statement outlining fails if the intermediate goal cannot be discharged. `transitivity *` should be used in this case.
=> Reworked outline tactic

src/ecCommands.ml, src/ecCorePrinting.ml, src/ecEnv.ml, src/ecEnv.mli, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecScope.ml, src/ecScope.mli, src/ecSection.ml, src/ecSubst.ml, src/ecThCloning.ml, src/ecTheory.ml, src/ecTheory.mli, src/ecTheoryReplay.ml, tests/theory-alias.ec
Syntax this: `theory T = Path.To.Theory`
Theory aliases allow giving alternate names to theories - mainly
for readability issues. They are purely syntactic sugar and are
fully resolved (desugared) during typing.
The pretty-printer uses them when printing path, using a
longest-then-lastly-introduced strategy.
=> New vernacular command: theory aliases

theories/algebra/Ring.ec
This allows using a Field instance in place of a Ring.
=> stdlib: in Field, do not erase the unit predicate

src/ecLexer.mll, src/ecParser.mly, src/ecParsetree.ml, src/ecPrinting.ml, src/ecScope.ml, src/ecSection.ml, src/ecSection.mli, src/ecTheoryReplay.ml, src/ecTheoryReplay.mli, tests/global_cloning.ec
This pull request adds a `global` keyword that ensures that
```
global clone A as Ab ...
```
gives public visibility to newly-cloned items from theory `A`. This might be useful in patterns like
```
local clone A as Ab.
global clone Ab.some.interesting.subtheory as B with ...
```
in order to reexport only specific parts of interest from a given theory `A`. It does not change the standard behaviour
that `clone A as B` preserves the visibility of `A` for items of `B`. Commit df336f872dcb62b571ece9c6670bcb4e41828932 provides an information message when this happens when cloning a local theory (with `clone` and not `local clone`), and also informs on the existence of the `global` keyword.
This also addresses issue #747, because it gives the right visibility to the new _theory_ itself, and not …
=> Keyword `global` for cloning theories

examples/ChaChaPoly/chacha_poly.ec, theories/crypto/SplitRO.ec
The theory `SplitRO.SplitCodom` from the standard library needlessly requires a bijection between the two spaces of interest, where only a left (or right, depending on your viewpoint) inverse is needed.
I admit willingly that the modifications are not very elegant, so I might be missing out on two ways to do it more cleanly:
- Is there a way to insert an `alias` statement at the _end_ of a program?
- Is it possible to transform the goal more simply than with `transitivity` (as `conseq` cannot work here)?  (This transformation is necessary as it allows `rndsem*` to only keep the right variables, which ultimately gives the same support on both sides).
=> [Theories, SplitRO] remove requirement of axiom `ofpairK`

src/ecParser.mly, src/ecParsetree.ml, src/ecTyping.ml, src/ecTyping.mli, tests/annotated-getter-setter.ec
This commit introduces the following syntax:
- `m.[:(ty) k]` for `(m.[k] :~ ty)`
- `m.[:(ty) k <- v]` for `m.[k <- (v :~ ty)]`
- `m.[:(ty) k] <- k` for `m.[k] <- (v :~ ty)`
This helps disambiguate the selection of getters and setters using the type of the map's values.
=> Type annotated getters/setters

src/ecSmt.ml
When abstracting out a construction that is not translatable into SMT, make the abstraction symbol depends on the local variables.
If not, the translation is unsound by making the translated constructions a constant. For example, the following (where G will be abtracted):
```
fun x => G[x]
```
is translated into
```
fun x => fresh-constant
```
=> Fix bug in SMT translation (abstraction of non-translatable constructions)

examples/RWhileSampling.ec, src/phl/ecPhlWhile.ml
Add tactic for one-sided while rule with lossless proof:
```   
{I} while b do c {T}   {I}c{I}   P => I /\ (not b => I => Q)
------------------------------------------------------------
{P} while b do c ~ skip {Q}
```
```
{I} while b do c {T}   {I}c{I}   P => I /\ (not b => I => Q)
------------------------------------------------------------
{P} skip ~ while b do c {Q}
```
=> Add tactic for lossless while

.github/workflows/ci.yml
Running `opam depext` with `confirm-level=unsafe-yes`. This allows `opam` to install missing external dependencies (via the host package manager)
=> depext -> confirm level = unsafe-yes

.gitignore, dune, dune-project, etc/README, etc/dune, src/ec.ml, src/ecRelocate.ml, src/ecRelocate.mli
At startup, EasyCrypt now loads all configuration files from `site:config` (default: `lib/easycrypt/config`) with a `.conf` extension. These files are processed in alphabetical order, after the main system-wide configuration file.
=> Introduce a system-wide, parts-oriented configuration file

theories/datatypes/BitEncoding.ec
New lemmas: `int2bs_strikeE`, `int2bs_strike_succE`
=> More results on `BitEncoding.int2bs`
