EasyCrypt/easycrypt

- src/ecScope.ml
> Swap the semantic of `` and `!` for smt provers option.

- src/ecHiGoal.ml
- src/ecLowGoal.ml
- src/ecLowGoal.mli
- src/ecParser.mly
- src/ecParsetree.ml
- src/ecProofTerm.ml
This revert pattern revert a local-binding as a let-in construct.
[closes #17291]
> New revert pattern: `@x`

- src/ecReduction.ml
- theories/distributions/Distr.ec
> eta-conversion should only be triggered on terms with compatible types

- theories/datatypes/FSet.ec
- theories/prelude/Logic.ec
> characterization lemmas for <=> and \proper

- README.md
I've formatted the README so it is easier to read. Additionally I've added:
- EasyCrypt title and blurb
- Add institution logos
- Table of Contents
- Moved `opam` installation up document and into its our section
Happy to make any additional changes in order for this to be accepted.
> Tidy up of README

- .gitignore
- .merlin
- .travis.yml
- Makefile
- _tags
- default.nix
- examples/Pedersen.ec
- examples/SchnorrPK.ec
- examples/prg-tutorial/PRF.eca
- examples/prg-tutorial/PRG.eca
- examples/prg-tutorial/PRGc.ec
- src/ec.ml
- src/ecCommands.ml
- src/ecCommands.mli
- src/ecCoreGoal.ml
- src/ecEco.ml
- src/ecHiGoal.ml
- src/ecHiGoal.mli
- src/ecLoader.ml
- src/ecLoader.mli
- src/ecLowGoal.ml
- src/ecLowGoal.mli
- src/ecScope.ml
- src/ecScope.mli
- src/phl/ecPhlAuto.ml
- theories/crypto/Commitment.ec
- theories/crypto/DLog.ec
- theories/crypto/SigmaProtocol.ec
Hey folks, I would like to merge the work I have done a couple of years ago to EC, to let it be more easily available to all who may benefit from it. 
Summary:
- formalisation of discrete logarithm game
- formalisation of commitment schemes
- formalisation of sigma protocols
- formalisation of the Pedersen commitment scheme
- formalisation of the Schnorr proof of knowledge (as sigma protocol example)
I hope I have purged the code from SMT solvers correctly.
Please, feel free to make any changes you want.
> Commitments and sigma protocols

- .travis.yml
- default.nix
- opam
- src/ecSmt.ml
- src/ecWhy3Conv.ml
Attempt at being compatible with Why3 1.3.X (and therefore incompatible with Why3 1.2.X)
> First attempt at handling Why3 1.3.X

- examples/ChaChaPoly/Indistinguishability.eca
- examples/ChaChaPoly/chacha_poly.ec
- examples/ChaChaPoly/ske.ec
- theories/algebra/Group.ec
- theories/analysis/RealExp.ec
- theories/core/Bool.ec
- theories/crypto/PROM.ec
- theories/crypto/ROM.eca
- theories/crypto/SplitRO.ec
- theories/datatypes/List.ec
- theories/datatypes/Tuple.eca
- theories/datatypes/Word.eca
- theories/distributions/DList.ec
- theories/distributions/Distr.ec
- theories/newth/SmtMap.ec
- theories/structure/FinType.ec
This is a soft-merge bringing the proof of ChaCha20+Poly1305 into 1.0.
This changes FinType in an annoying way, which we might want to change before merging.
Everything else is additions (including the addition of a third RO-related file...)
> Merge chachapoly

- examples/ChaChaPoly/chacha_poly.ec
- theories/datatypes/List.ec
- theories/newth/SmtMap.ec
Add basic support for has and find on SmtMaps.
> Deploy map find

- src/ecTyping.ml
Make formula slices inclusive.
This doesn't completely solve the problem as slices with negative indices still don't make sense.
> First pass: slices are inclusive

- src/ecOptions.ml
- src/ecOptions.mli
> Add rdirs option in config file

- theories/crypto/PROM.ec
- theories/structure/FinType.ec
This is the random oracle with unit domain and a single variable as internal memory discussed [on Zulip](https://formosa-crypto.zulipchat.com/#narrow/stream/308381-EasyCrypt.3A-questions.20.26.20features/topic/.E2.9C.94.20Unroll.20while.20loop.3F)
> eager random oracle for unit domain (single random variable)

- theories/structure/WF.ec
> An axiom-free formalization of well-founded relations, induction

- theories/datatypes/List.ec
Added definition and lemmas for 'set' operator in List.ec.
> Pull request concerning Issue #123: Feature request for replace/set operator.

- theories/algebra/IntDiv.ec
> add a basic lemma to the standard library

- src/ecHiGoal.ml
> [tactic]: in `apply... in...`, check that all variables are instantiated

- src/ecHiGoal.ml
`rewrite h` with `h : eq1 /\ eq2 /\ ... /\ eqn` is equivalent
to `rewrite ?(h1, h2, ..., hn)` with `hi : eqi`
address #155
> [tactic]: [rewrite]: support for multi-rules

- examples/cramer-shoup/cramer_shoup.ec
- src/ecCallbyValue.ml
- src/ecFol.ml
- theories/distributions/Distr.ec
- theories/structure/Discrete.ec
> [reduction]: use symmetric "and" when reducing tuples equality

- src/ecCallbyValue.ml
- src/ecEnv.ml
> Fix various bugs w.r.t. reduction and printing of match expressions.

- examples/ChaChaPoly/chacha_poly.ec
- src/ecCoreModules.ml
- src/ecCoreModules.mli
- src/ecEnv.ml
- src/ecFol.ml
- src/ecFol.mli
- src/ecMemory.ml
- src/ecMemory.mli
- src/ecPV.ml
- src/ecParser.mly
- src/ecParsetree.ml
- src/ecPrinting.ml
- src/ecSection.ml
- src/ecSubst.ml
- src/ecTypes.ml
- src/ecTypes.mli
- src/ecTyping.ml
- src/ecTyping.mli
- src/ecUserMessages.ml
- src/phl/ecPhlCodeTx.ml
- src/phl/ecPhlEager.ml
- src/phl/ecPhlEqobs.ml
- src/phl/ecPhlFel.ml
- src/phl/ecPhlFun.ml
- src/phl/ecPhlInline.ml
- src/phl/ecPhlPr.ml
- src/phl/ecPhlRCond.ml
(Partially) Resolves #108.
This doesn't allow partially anonymous parameter lists.
> Improve parser for anonymous proc parameters

- .github/workflows/ci.yml
- scripts/docker/base-box/Dockerfile
- scripts/docker/base-box/sudoers
- scripts/docker/build-box/Dockerfile
- scripts/docker/test-box/Dockerfile
This requires a modification of the docker image s.t. the user UID is compatible with the one used by Github Action
> [github-action]: do not start as root

- dune-project
- easycrypt.opam
- src/ecProvers.ml
> Bump Why3 version from 1.4.x to 1.5.0

- scripts/testing/runtest
- src/ec.ml
- src/ecOptions.ml
- src/ecOptions.mli
- src/ecProvers.ml
- src/ecTerminal.ml
- src/ecTerminal.mli
- more readable output (for tty / no-tty)
- more readable report
> New `runtest` script

- theories/algebra/IntDiv.ec
- theories/algebra/Number.ec
- theories/algebra/Poly.ec
- theories/algebra/Ring.ec
- theories/algebra/StdOrder.ec
- theories/algebra/ZModP.ec
- theories/analysis/RealExp.ec
- theories/datatypes/BitEncoding.ec
- theories/datatypes/Int.ec
- theories/datatypes/IntMin.ec
- theories/datatypes/List.ec
- theories/datatypes/Real.ec
- theories/looping/IterProc.eca
- theories/prelude/Logic.ec
- theories/structure/Discrete.ec
Theories needed for the hakyber proof.
Only automatic test that fails is theories/algebra/ZModP.ec, for already identified smt reasons.
> Hakyber jasmin eclib

- .github/workflows/ci.yml
Currently, this mechanism is configured to check the Jasmin ECLib
> CI: mechanism for checking external developments

- src/ecScope.ml
> Fix a typing annotation bug in distribution tags' axioms

- src/ecSection.ml
> Enforce section restrictions on the types of declared modules.

- src/ecTheoryReplay.ml
Currently, when the reduction rule does not exist anymore (because
it has been removed by the inlining mechanism), the cloning fails
with a lookup error.
Ref #247
> When replaying a reduction rule, check that the rule does still exists.

- src/ecCoreFol.ml
- src/ecCoreFol.mli
- src/ecCoreModules.ml
- src/ecHiGoal.ml
- src/ecParsetree.ml
- src/ecPath.ml
- src/ecPath.mli
- src/ecReduction.ml
- src/ecSubst.ml
- src/ecSubst.mli
- src/ecThCloning.ml
- src/ecTheoryReplay.ml
- src/ecTypes.ml
- src/ecTypes.mli
> Fix various bugs that relate to theories cloning

- theories/distributions/Distr.ec
Just some lemmas I needed while bounding an adversaries ability to bound randomly sampled values.
> Lemmas on dprod and djoin

- src/ecHiGoal.ml
> In tactic apply[alpha]: instiantiate type-varaibles.

- src/ecReduction.ml
> [conv]: add case for program variables

- theories/distributions/Distr.ec
Will add more on min-entropy later, but that seems to require adding some more "basic" operations and lemma in a few different places. That'll probably fit better in a separate pull request.
> Add conditional probability distributions

- src/phl/ecPhlHiAuto.ml
> lossless for equiv

- examples/upto_syntaxtic.ec
- src/ecCoreLib.ml
- src/ecCoreLib.mli
- src/ecHiTacticals.ml
- src/ecLexer.mll
- src/ecParser.mly
- src/ecParsetree.ml
- src/ecReduction.ml
- src/ecReduction.mli
- src/phl/ecPhlDeno.ml
- src/phl/ecPhlUpto.ml
- src/phl/ecPhlUpto.mli
- theories/algebra/Number.ec
- theories/algebra/StdOrder.ec
- theories/datatypes/Real.ec
There is a example file in: 
examples/upto_syntaxtic.ec
please play with it.
> add syntaxic upto tactic

- src/ecTheoryReplay.ml
A local exception was raised but was not properly catched.
Fix #268
> Fix a bug when replaying a removed user reduction rule

- examples/upto_syntaxtic.ec
- src/phl/ecPhlUpto.ml
Sorry I was too fast in my previous pull request. I think the check is correct now.
> add missing restriction in the case of adversary

- theories/distributions/Dexcepted.ec
- theories/distributions/Dfilter.ec
- theories/distributions/Distr.ec
> port Dexcepted to dresrict and deprecate Dfilter

- src/ecUserMessages.ml
I found this typo.
Also, I need a quick win with an easy PR :P
> Fix typos in user messages

- theories/analysis/RealSeries.ec
- theories/core/Core.ec
- theories/distributions/Distr.ec
- theories/structure/FinType.ec
- theories/structure/Finite.ec
Except the new theory Dfun_sub in Distr, the lemmas come from branch deploy-quantum
> add theory Dfun_sub + backport many lemma from deploy-quantum

- theories/distributions/Distr.ec
The lemma dfun_dmap comes from deploy-quantum.
The lemmas dlet_dfun, dfun_unit and dmap_dfun are news.
> add few lemmas on dfun

- src/ecCorePrinting.ml
- src/ecEnv.mli
- src/ecHiGoal.ml
- src/ecMatching.ml
- src/ecParsetree.ml
- src/ecReduction.ml
- src/ecThCloning.ml
- src/ecTheoryReplay.ml
> Various bug fixes for clones (modules & lemmas)

- dune
- dune-project
- scripts/testing/bin-ec-runtest
- src/dune
- src/ec.ml
- src/ecOptions.ml
- src/ecOptions.mli
- src/ecRelocate.mli
- the subcommand is named `runtest`
- the real script is now in `<libexec>/easycrypt/commands/`
> [CLI]: ec-runtest is now accessible via a CLI subcommand

- src/ecHiGoal.ml
- src/ecHiGoal.mli
- src/ecHiTacticals.ml
- src/ecLowGoal.ml
- src/ecLowGoal.mli
- src/ecParser.mly
- src/ecParsetree.ml
The syntax is `pose &m`.
Close #320
> [tactic]: add the ability to create a memory from thin air.

- src/ecTyping.ml
This seems to solve the problem I was having here #323, though I'm not sure it's the most efficient of solutions.
> Fix for #323, open types after `if is` branch

- src/ecSmt.ml
> Fix encoding of Why3 fixpoint containing higher-order calls to itself

- theories/algebra/Bigalg.ec
- theories/analysis/RealSeries.ec
- theories/datatypes/Int.ec
- theories/datatypes/List.ec
- theories/distributions/DBool.ec
- theories/distributions/SDist.ec
- theories/structure/Finite.ec
Some more lemmas from our supplementary file that don't follow any overarching theme.
> [theories]: add various individual lemmas

- README.md
- default.nix
- dune-project
- easycrypt.opam
- examples/MEE-CBC/CBC.eca
- examples/MEE-CBC/MAC_then_Pad_then_CBC.eca
- shell.nix
- src/ecProvers.ml
- src/ecSmt.ml
- src/ecUtils.ml
- theories/algebra/StdBigop.ec
- theories/algebra/StdOrder.ec
- theories/crypto/prp_prf/Strong_RP_RF.eca
This makes EC compatible with OCaml 5.
Close #350
> Bump Why3 supported version (1.5 -> 1.6)

- examples/Dice4_6.ec
- examples/MEE-CBC/CBC.eca
- examples/UC/RndO.ec
- examples/rwequiv.ec
- src/ecFol.ml
- src/ecFol.mli
- src/ecHiGoal.ml
- src/ecLowGoal.ml
- src/ecLowGoal.mli
- src/ecParser.mly
- src/ecParsetree.ml
- src/ecTyping.ml
- src/ecTyping.mli
- src/phl/ecPhlTrans.mli
- theories/crypto/PRP.eca
- theories/crypto/ROM.eca
- theories/crypto/SplitRO.ec
- theories/crypto/prp_prf/Strong_RP_RF.eca
- theories/distributions/DList.ec
- theories/distributions/SDist.ec
- theories/looping/FoldProc.eca
See the [wiki page](https://github.com/EasyCrypt/easycrypt/wiki/%5BTactic%5D-Rewrite-Equiv) for usage details. Also, not sure if the changes to examples/standard lib are desired or not.
> [Tactic] Rewrite Equiv

- src/ecHiGoal.ml
- theories/crypto/ROM.eca
This fixes the anomalies from #362. It also updates a proof in the standard library that was missed with the first PR.
> Fix for #362, handle anomalies in rewrite equiv

- .github/workflows/ci.yml
+ [x] Upgrade nix actions
+ [x] Upgrade conclusion action
+ [ ] Upgrade zulip messaging action
> Update ci configuration

- theories/crypto/PROM.ec
as discussed [on Zulip](https://formosa-crypto.zulipchat.com/#narrow/stream/308381-EasyCrypt.3A-questions-.26-features/topic/FunRO) 
Invariant inspired by  `init_eager` on `deploy-qrom-update:T_QROM`  (basically the same for `ROM`)
> [theories] FunRO: RO for FinType using dfun for init

- src/ecHiNotations.ml
> Accept non-printed variable only abbreviations.

- theories/datatypes/FSet.ec
A very small PR to add a simple facts about sets of size 1.
> [lib] FSet: fcard_eq1

- theories/algebra/PolyReduce.ec
Add choice-based inverses and fix broken proofs from subtype changes
> Take PolyReduce theory from Kyber project

- examples/tactics/inline.ec
- src/ecHiGoal.ml
- src/ecParser.mly
- src/ecParsetree.ml
- src/phl/ecPhlInline.ml
I realised my Zulip message never got any reply so I am creating a PR to raise attention to what we did with @bgregoir.
This new inline allows patterns, positively or negatively specified. This should make it possible to control what to inline more easily. Could you have a look at it and possibly try it for yourself so that we can hear your feedback on this new syntax?
You will be able to find examples at the following link.
https://github.com/EasyCrypt/easycrypt/blob/deploy-inline/examples/tactics/inline.ec
> New inline

- theories/analysis/RealSeries.ec
- theories/structure/Discrete.ec
Maybe you should change the name of this lemma ...
> add lemma on summable

- src/ecScope.ml
Do the operator substitution and then close the formula.
> op: fix creation of refined operators

- src/ecCoreFol.ml
If not, the substitution can lead to name captures.
> In subst, when crossing a binding, remove the bound variable.

- src/ecLowGoal.ml
> When rewriting in the local env, do not fail on identity rewriting

- scripts/testing/runtest
- src/ec.ml
Again, Jasmin CI is expected to fail.
> runtest: new option: why3 (why3 configuration file location)

- .github/workflows/ci.yml
- Makefile
- config/tests.config
- tests/req_allcore.ec
In the automated tests, add a section `unit`for unit tests.
The unit tests are checked by the CI.
They can be run using `make unit`.
> CI: unit tests

- .github/workflows/ci.yml
If so, we can end with PR to protected branches that are blocked.
> CI: do not skip successful duplicates

- .github/workflows/ci.yml
- .github/workflows/external.json
Check is done in weak-check mode.
> [ci] add ML-KEM

- .github/workflows/ci.yml
Command has been marked as deprecated
> [ci] do not use set-output anymore

- scripts/testing/runtest
This is so we might get useful CI logs.
> [runtest] fix TTY detection

- theories/distributions/Distr.ec
> make dapply a parsing-only abbreviation

- src/ecDecl.ml
- src/ecDecl.mli
- src/ecEnv.ml
- src/ecHiPredicates.ml
- src/ecInductive.ml
- src/ecScope.ml
- src/ecSection.ml
- src/ecSmt.ml
- src/ecTheoryReplay.ml
Operators' body are not sent to SMT solvers when tagged with "smt_opaque"
> New tags for operators: smt_opaque

- theories/prelude/Logic.ec
Very simple lemmas that allow to reduce if-expression.
> [stdlib]: iftrue / iffalse

- src/ecCoreFol.ml
- src/ecCoreFol.mli
- src/ecFol.ml
- src/ecFol.mli
- src/ecPrinting.ml
- src/phl/ecPhlExists.ml
When a bound is given to elim*, do not try to destruct internal existentials.
> Fixing bug in elim* when a bound is given.

- theories/distributions/Distr.ec
dprod_dunit, dprod_marginal{L,R}, dprod_dmap_cross, dprod_dmap
> [stdlib]: extra lemmas on dprod.

- theories/distributions/DList.ec
> [stdlib]: more lemmas on distributions over lists

- scripts/testing/runtest
> runtest: display number of parallel jobs

- examples/ehoare/adversary.ec
- theories/datatypes/Xreal.ec
These might enable a version bump on some provers.
> remove some edgy SMTs in Xreal and related

- src/ecThCloning.ml
- src/ecThCloning.mli
- src/ecTheoryReplay.ml
- src/ecUserMessages.ml
> cloning: do not allow realizing a non-axiomatic lemma

- scripts/testing/runtest
> runtest: lint code + fix warnings

- src/ecCallbyValue.ml
- src/ecReduction.ml
Record projectors being operators, they are subject to user defined rules.
Fix #319
> user reduction: fix some incompleteness issues

- .github/workflows/ci.yml
- Makefile
- src/dune
> ci: compile with warning as errors

- src/ecParser.mly
- src/ecParsetree.ml
- src/ecPrinting.ml
- src/ecTyping.ml
Fix #181 (but for the last point: see #621)
> pretty-printer/parser: improve reparsability of the pretty-printer output

- src/phl/ecPhlRewrite.ml
- tests/procrewrite.ec
Fixes memory selection in expr_of_form in proc rewrite and adds a test for prhl proc rewrite.
> PR: Fix for proc rewrite in prhl

- src/ecPrinting.ml
The output can now be reparsed
Fix #183
> pretty-printing: rework the pretty-printing of module restrictions

- src/ecLoader.ml
Especially useful on case-insenstive, case-preserving file systems
Fix #640
> In error messages, use the correct filename casing

- src/ecPath.ml
- src/ecPath.mli
- src/ecSection.ml
- src/ecSubst.ml
- src/ecSubst.mli
- src/ecTheoryReplay.ml
- tests/generalize-module-aliases.ec
> sections: expand&clear module aliases that contain generalized modules

- src/ecTheoryReplay.ml
> no user defined rule in op comparison

- src/ecParser.mly
> Fix deep code positions parsing

- src/ecEnv.ml
- src/ecEnv.mli
- src/ecPrinting.ml
Fix various fixes of the current pretty printer.
> PP: various fixes

- dune-project
- easycrypt.opam
- flake.lock
- flake.nix
- scripts/docker/Dockerfile.base
- scripts/docker/Dockerfile.build
- bump dune to 3.13 (needed for passing the --explain flag to menhir)
- bump all provers subsubminor (in nix & Docker)
- bump nix to 24.05 & fix compilation issues
- revert OCaml to 4.14.2 in Docker
> Service commit (docker / nix / dune)

- theories/datatypes/FMap.ec
> Add lemma: ge0_fsize

- src/ecPrinting.ml
> Pretty printer: print terminator after module types

- .github/workflows/ci.yml
The ubuntu-20.04 image is now unsupported
> CI: update image from ubuntu-20.04 to ubuntu-24.04

- src/phl/ecPhlWhile.ml
- theories/looping/LoopTransform.ec
fix #774
some conditions where missing in the async while rule ...
> fix async while rule

- src/phl/ecPhlUpto.ml
- tests/upto_adv.ec
- tests/upto_fail_adv.ec
- tests/upto_fail_write_bad_false.ec
> fixes bug #785, add check that bad is only set to true once set

- src/phl/ecPhlPrRw.ml
- tests/rw_mu_has_le.ec
> add mu_has_le in rewrite Pr
